.\" groff -man -Tascii pward.1
.\" groff -man -Tascii pward.1 | col -b
.TH PWARD 1 "July 2010" Linux "User Manuals"
.SH NAME
pward \- monitor the lifecycle of a set of processes.
.SH SYNOPSIS
.B pward
[
.I OPTION
] ... [
.I
PID
] ...
.SH DESCRIPTION
.B pward
monitors a set of processes given at the command-line. By default,
pward stops when all specified processes have died.
Optionnally, it stops when a specified number of processes has stopped,
or when less than a specified number of processes is still running.
It can be configured to execute a specified command before stopping.
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-running\fR=n
stop monitoring when no more than n processes are still running (default 0)
.TP
\fB\-s\fR, \fB\-\-stopped\fR=n
stop monitoring when at least n processes have stopped (default 1)
.TP
\fB\-e\fR, \fB\-\-exec\fR=\fIcommand\fR
Execute \fIcommand\fR after the treshold is met, and before pward is stopped.
The command  is executed in the starting directory.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
summarize monitored processes at startup.
.TP
\fB\-b\fR, \fB\-\-batch\fR
don't perform sanity checks at input. This can be useful when invoked from a script.
.TP
\fB\-h\fR, \fB\-\-help\fR
print a help message at startup.
.TP
\fB[PID]\fR
space separated list of process-ids to be monitored. 

.SH FILES

.SH ENVIRONMENT

.SH DIAGNOSTICS
The following diagnostics may be issued on stderr:

non numeric parameter
.RS
The input parameter is not a number.
.RE

command failed
.RS
the command in the -exec option failed to execute.
.RE

.SH BUGS
pward checks processes by polling the proc-table.
This is portable, but an implementation with modern kernel features would be more efficient.

.SH EXAMPLES
.B pward `pgrep emerge` -v -i10 -e"shutdown -h +10"

Shuts down the machine 10 minutes after emerge finished.
Some info about the monitored processes is dumped to the console at startup.
The polling interval is set to 10 seconds.
The user needs the rights to shutdown the machine for this to work.

.SH AUTHOR
Dirk Moermans <dirkmoermans @ gmail.com>
.SH "SEE ALSO"
.BR pgrep (1),
.BR pkill (1),
.BR top (1)
